import { CategoryPath } from './categoryPath.interface'
import { Shipping } from './shipping.interface'

export interface Product {
  sku: number,
  score: string,
  productId: string,
  name: string,
  source: string,
  type: string,
  startDate: string,
  new: boolean,
  active: boolean,
  lowPriceGuarantee: boolean,
  activeUpdateDate: string,
  regularPrice: number,
  salePrice: number,
  clearance: boolean,
  onSale: boolean,
  planPrice: string,
  priceWithPlan: [],
  contracts: [],
  priceRestriction: string,
  priceUpdateDate: string,
  digital: boolean,
  preowned: boolean,
  carriers: [],
  planFeatures: [],
  devices: [],
  carrierPlans: [],
  technologyCode: string,
  carrierModelNumber: string,
  earlyTerminationFees: [],
  monthlyRecurringCharge: number,
  monthlyRecurringChargeGrandTotal: number,
  activationCharge: number,
  minutePrice: number,
  planCategory: string,
  planType: string,
  familyIndividualCode: string,
  validFrom: string,
  validUntil: string,
  carrierPlan: string,
  outletCenter: string,
  secondaryMarket: string,
  frequentlyPurchasedWith: [],
  accessories: [],
  relatedProducts: [],
  requiredParts: [],
  techSupportPlans: [],
  crossSell: [],
  salesRankShortTerm: string,
  salesRankMediumTerm: string,
  salesRankLongTerm: string,
  bestSellingRank: string,
  url: string,
  spin360Url: string,
  mobileUrl: string,
  affiliateUrl: string,
  addToCartUrl: string,
  affiliateAddToCartUrl: string,
  linkShareAffiliateUrl: string,
  linkShareAffiliateAddToCartUrl: string,
  upc: string,
  productTemplate: string,
  categoryPath: CategoryPath[],
  alternateCategories: CategoryPath[],
  lists: [],
  customerReviewCount: number,
  customerReviewAverage: number,
  customerTopRated: boolean,
  format: string,
  freeShipping: boolean,
  freeShippingEligible: boolean,
  inStoreAvailability: boolean,
  inStoreAvailabilityText: string,
  inStoreAvailabilityUpdateDate: string,
  itemUpdateDate: string,
  onlineAvailability: boolean,
  onlineAvailabilityText: string,
  onlineAvailabilityUpdateDate: string,
  releaseDate: string,
  shippingCost: number,
  shipping: Shipping[],
  shippingLevelsOfService: [
    {
      serviceLevelId: 5,
      serviceLevelName: One Day,
      unitShippingPrice: 57.79
    },
    {
      serviceLevelId: 3,
      serviceLevelName: Two Day,
      unitShippingPrice: 30.79
    },
    {
      serviceLevelId: 21,
      serviceLevelName: Standard,
      unitShippingPrice: 0
    }
  ],
  specialOrder: boolean,
  shortDescription: RefurbishedWindows 10 ProTechnical details: 3rd Gen Intel&#174; Core&#8482; i5 processor; 8GB memory; 1TB hard driveSpecial features: keyboard and mouse,
  class: DESK TOP COMPUTERS,
  classId: 85,
  subclass: SO RFRB DESKTOP,
  subclassId: 179,
  department: COMPUTERS,
  departmentId: 6,
  protectionPlanTerm: HP ,
  protectionPlanType: string,
  protectionPlanLowPrice: ,
  protectionPlanHighPrice: ,
  buybackPlans: [],
  protectionPlans: [],
  protectionPlanDetails: [],
  productFamilies: [],
  productVariations: [],
  aspectRatio: string,
  screenFormat: string,
  lengthInMinutes: string,
  mpaaRating: string,
  plot: string,
  studio: string,
  theatricalReleaseDate: string,
  description: string,
  manufacturer: HP,
  modelNumber: HP8300SFF.8GB.1TB.WIN10,
  images: [
    {
      rel: Front_Zoom,
      unitOfMeasure: pixels,
      width: 1000,
      height: 1000,
      href: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sd.jpg,
      primary: boolean
    },
    {
      rel: Front_Detail,
      unitOfMeasure: pixels,
      width: 105,
      height: 105,
      href: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sc.jpg,
      primary: boolean
    },
    {
      rel: Front_Medium,
      unitOfMeasure: pixels,
      width: 70,
      height: 70,
      href: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109fp.gif,
      primary: boolean
    },
    {
      rel: Front_Standard,
      unitOfMeasure: pixels,
      width: 500,
      height: 500,
      href: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sa.jpg,
      primary: boolean
    },
    {
      rel: Front_Thumbnail,
      unitOfMeasure: pixels,
      width: 54,
      height: 54,
      href: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_s.gif,
      primary: boolean
    },
    {
      rel: Front_Large,
      unitOfMeasure: pixels,
      width: 160,
      height: 160,
      href: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sb.jpg,
      primary: boolean
    }
  ],
  image: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sa.jpg,
  largeFrontImage: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sd.jpg,
  mediumImage: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109fp.gif,
  thumbnailImage: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_s.gif,
  largeImage: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sb.jpg,
  alternateViewsImage: string,
  angleImage: string,
  backViewImage: string,
  energyGuideImage: string,
  leftViewImage: string,
  accessoriesImage: string,
  remoteControlImage: string,
  rightViewImage: string,
  topViewImage: string,
  albumTitle: Refurbished Compaq Desktop - Intel Core i5 - 8GB Memory - 1TB Hard Drive,
  artistName: string,
  artistId: string,
  originalReleaseDate: string,
  parentalAdvisory: string,
  mediaCount: string,
  monoStereo: string,
  studioLive: string,
  condition: Refurbished,
  inStorePickup: boolean,
  friendsAndFamilyPickup: boolean,
  homeDelivery: boolean,
  quantityLimit: 3,
  fulfilledBy: string,
  members: [],
  bundledIn: [],
  albumLabel: string,
  genre: string,
  color: Black,
  depth: 14.9 inches,
  dollarSavings: 120,
  percentSavings: 36.36,
  tradeInValue: ,
  height: 4 inches,
  orderable: Available,
  weight: 16.7 pounds,
  shippingWeight: 20,
  width: 13.3 inches,
  warrantyLabor: 18 months,
  warrantyParts: 18 months,
  softwareAge: string,
  softwareGrade: string,
  platform: string,
  numberOfPlayers: string,
  softwareNumberOfPlayers: string,
  esrbRating: string,
  longDescription: Refurbished HP Compaq Desktop: Increase your productivity with this HP Compaq Elite computer. Its generous 8GB of RAM and Intel Core processor keep things humming, and its 1TB hard drive stores all your programs, photos and movies handily. This small form factor HP Compaq Elite computer has Windows 10 preinstalled, so you can stay current on security updates effortlessly.,
  includedItemList: [
    {
      includedItem: Refurbished HP Compaq Elite 8300
    },
    {
      includedItem: Mouse, keyboard
    }
  ],
  marketplace: string,
  listingId: string,
  sellerId: string,
  shippingRestrictions: string,
  proposition65WarningMessage: string,
  proposition65WarningType: 05,
  driveCapacityGb: 1000,
  energyStarQualified: boolean,
  ethernetPort: boolean,
  mobileOperatingSystem: Windows 10 Home,
  usbPort: boolean

}
