export interface SearchData {
    from: number,
    to: number,
    currentPage: number,
    total: number,
    totalPages: number,
    queryTime: number,
    totalTime: number,
    partial: boolean,
    canonicalUrl: string,
    "products": [
      {
        "sku": 5710109,
        "score": null,
        "productId": null,
        "name": "HP - Refurbished Compaq Desktop - Intel Core i5 - 8GB Memory - 1TB Hard Drive - Black",
        "source": null,
        "type": "HardGood",
        "startDate": "2016-12-18",
        "new": false,
        "active": true,
        "lowPriceGuarantee": false,
        "activeUpdateDate": "2020-02-28T15:28:46",
        "regularPrice": 329.99,
        "salePrice": 209.99,
        "clearance": false,
        "onSale": true,
        "planPrice": null,
        "priceWithPlan": [],
        "contracts": [],
        "priceRestriction": null,
        "priceUpdateDate": "2020-09-02T00:01:48",
        "digital": false,
        "preowned": false,
        "carriers": [],
        "planFeatures": [],
        "devices": [],
        "carrierPlans": [],
        "technologyCode": null,
        "carrierModelNumber": null,
        "earlyTerminationFees": [],
        "monthlyRecurringCharge": "",
        "monthlyRecurringChargeGrandTotal": "",
        "activationCharge": "",
        "minutePrice": "",
        "planCategory": null,
        "planType": null,
        "familyIndividualCode": null,
        "validFrom": null,
        "validUntil": null,
        "carrierPlan": null,
        "outletCenter": null,
        "secondaryMarket": null,
        "frequentlyPurchasedWith": [],
        "accessories": [],
        "relatedProducts": [],
        "requiredParts": [],
        "techSupportPlans": [],
        "crossSell": [],
        "salesRankShortTerm": null,
        "salesRankMediumTerm": null,
        "salesRankLongTerm": null,
        "bestSellingRank": null,
        "url": "https://api.bestbuy.com/click/-/5710109/pdp",
        "spin360Url": null,
        "mobileUrl": "https://api.bestbuy.com/click/-/5710109/pdp",
        "affiliateUrl": null,
        "addToCartUrl": "https://api.bestbuy.com/click/-/5710109/cart",
        "affiliateAddToCartUrl": null,
        "linkShareAffiliateUrl": "",
        "linkShareAffiliateAddToCartUrl": "",
        "upc": "812177028899",
        "productTemplate": "Desktop_Computer_Towers",
        "categoryPath": [
          {
            "id": "cat00000",
            "name": "Best Buy"
          },
          {
            "id": "abcat0500000",
            "name": "Computers & Tablets"
          },
          {
            "id": "abcat0501000",
            "name": "Desktop & All-in-One Computers"
          },
          {
            "id": "pcmcat143400050013",
            "name": "All Desktops"
          }
        ],
        "alternateCategories": [
          {
            "id": "pcmcat212600050008",
            "name": "Computer Towers"
          }
        ],
        "lists": [],
        "customerReviewCount": 50,
        "customerReviewAverage": 3.4,
        "customerTopRated": false,
        "format": null,
        "freeShipping": true,
        "freeShippingEligible": true,
        "inStoreAvailability": true,
        "inStoreAvailabilityText": null,
        "inStoreAvailabilityUpdateDate": "2020-09-27T05:18:13",
        "itemUpdateDate": "2020-09-28T02:32:27",
        "onlineAvailability": true,
        "onlineAvailabilityText": null,
        "onlineAvailabilityUpdateDate": "2020-09-27T05:18:13",
        "releaseDate": null,
        "shippingCost": 0,
        "shipping": [
          {
            "ground": "",
            "secondDay": 30.79,
            "nextDay": 57.79,
            "vendorDelivery": ""
          }
        ],
        "shippingLevelsOfService": [
          {
            "serviceLevelId": 5,
            "serviceLevelName": "One Day",
            "unitShippingPrice": 57.79
          },
          {
            "serviceLevelId": 3,
            "serviceLevelName": "Two Day",
            "unitShippingPrice": 30.79
          },
          {
            "serviceLevelId": 21,
            "serviceLevelName": "Standard",
            "unitShippingPrice": 0
          }
        ],
        "specialOrder": false,
        "shortDescription": "RefurbishedWindows 10 ProTechnical details: 3rd Gen Intel&#174; Core&#8482; i5 processor; 8GB memory; 1TB hard driveSpecial features: keyboard and mouse",
        "class": "DESK TOP COMPUTERS",
        "classId": 85,
        "subclass": "SO RFRB DESKTOP",
        "subclassId": 179,
        "department": "COMPUTERS",
        "departmentId": 6,
        "protectionPlanTerm": "HP ",
        "protectionPlanType": null,
        "protectionPlanLowPrice": "",
        "protectionPlanHighPrice": "",
        "buybackPlans": [],
        "protectionPlans": [],
        "protectionPlanDetails": [],
        "productFamilies": [],
        "productVariations": [],
        "aspectRatio": null,
        "screenFormat": null,
        "lengthInMinutes": null,
        "mpaaRating": null,
        "plot": null,
        "studio": null,
        "theatricalReleaseDate": null,
        "description": null,
        "manufacturer": "HP",
        "modelNumber": "HP8300SFF.8GB.1TB.WIN10",
        "images": [
          {
            "rel": "Front_Zoom",
            "unitOfMeasure": "pixels",
            "width": "1000",
            "height": "1000",
            "href": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sd.jpg",
            "primary": true
          },
          {
            "rel": "Front_Detail",
            "unitOfMeasure": "pixels",
            "width": "105",
            "height": "105",
            "href": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sc.jpg",
            "primary": false
          },
          {
            "rel": "Front_Medium",
            "unitOfMeasure": "pixels",
            "width": "70",
            "height": "70",
            "href": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109fp.gif",
            "primary": false
          },
          {
            "rel": "Front_Standard",
            "unitOfMeasure": "pixels",
            "width": "500",
            "height": "500",
            "href": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sa.jpg",
            "primary": false
          },
          {
            "rel": "Front_Thumbnail",
            "unitOfMeasure": "pixels",
            "width": "54",
            "height": "54",
            "href": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_s.gif",
            "primary": false
          },
          {
            "rel": "Front_Large",
            "unitOfMeasure": "pixels",
            "width": "160",
            "height": "160",
            "href": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sb.jpg",
            "primary": false
          }
        ],
        "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sa.jpg",
        "largeFrontImage": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sd.jpg",
        "mediumImage": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109fp.gif",
        "thumbnailImage": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_s.gif",
        "largeImage": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5710/5710109_sb.jpg",
        "alternateViewsImage": null,
        "angleImage": null,
        "backViewImage": null,
        "energyGuideImage": null,
        "leftViewImage": null,
        "accessoriesImage": null,
        "remoteControlImage": null,
        "rightViewImage": null,
        "topViewImage": null,
        "albumTitle": "Refurbished Compaq Desktop - Intel Core i5 - 8GB Memory - 1TB Hard Drive",
        "artistName": null,
        "artistId": null,
        "originalReleaseDate": null,
        "parentalAdvisory": null,
        "mediaCount": null,
        "monoStereo": null,
        "studioLive": null,
        "condition": "Refurbished",
        "inStorePickup": true,
        "friendsAndFamilyPickup": true,
        "homeDelivery": false,
        "quantityLimit": 3,
        "fulfilledBy": null,
        "members": [],
        "bundledIn": [],
        "albumLabel": null,
        "genre": null,
        "color": "Black",
        "depth": "14.9 inches",
        "dollarSavings": 120,
        "percentSavings": "36.36",
        "tradeInValue": "",
        "height": "4 inches",
        "orderable": "Available",
        "weight": "16.7 pounds",
        "shippingWeight": 20,
        "width": "13.3 inches",
        "warrantyLabor": "18 months",
        "warrantyParts": "18 months",
        "softwareAge": null,
        "softwareGrade": null,
        "platform": null,
        "numberOfPlayers": null,
        "softwareNumberOfPlayers": null,
        "esrbRating": null,
        "longDescription": "Refurbished HP Compaq Desktop: Increase your productivity with this HP Compaq Elite computer. Its generous 8GB of RAM and Intel Core processor keep things humming, and its 1TB hard drive stores all your programs, photos and movies handily. This small form factor HP Compaq Elite computer has Windows 10 preinstalled, so you can stay current on security updates effortlessly.",
        "includedItemList": [
          {
            "includedItem": "Refurbished HP Compaq Elite 8300"
          },
          {
            "includedItem": "Mouse, keyboard"
          }
        ],
        "marketplace": null,
        "listingId": null,
        "sellerId": null,
        "shippingRestrictions": null,
        "proposition65WarningMessage": null,
        "proposition65WarningType": "05",
        "driveCapacityGb": 1000,
        "energyStarQualified": false,
        "ethernetPort": true,
        "mobileOperatingSystem": "Windows 10 Home",
        "usbPort": true
      }

}
